define([], function () {
  return {
    PropertyPaneDescription: "React Query Forum",
    BasicGroupName: "",
    LoadingCompnent: "Loading Component...",
    Fetching: "Fetching data",
    Sending: "Sending data",
    Error: 'Error connecting to server',
    DevTools: "Devtools",
    Visible: "Visible",
    Hidden: "Hidden",
    Topics: "Topics",
    Posts: "Posts",
    WaitListGeneration: 'Please wait..., React Query Forums lists will be generated soon',
    Name: "Name",
    TopicsPosts: 'Topics/Posts',
    LastPost: 'Last Post',
    Close: "Close",
    NewForum: "New Forum",
    Confirm: 'Confirm',
    Delete: 'Delete',
    Cancel: 'Cancel',
    Forum: 'Forum',
    EditForum: 'Edit Forum',
    TitleRequired: 'Title is required',
    DescriptionRequired: 'Description is required',
    ForumName: 'Forum Title',
    ForumDescription: 'Forum Description',
    Delete: 'Delete',
    Save: 'Save',
    Add: 'Add',
    Update: 'Update',
    ConfirmDelete: 'Are you sure you want to delete the',
    Loading: 'Loading...',
    MessageRequired: 'Message is required',
    RepliesViews: 'Replies/Views',
    Replies: 'Replies',
    Views: 'Views',
    NewTopic: 'New Topic',
    TopicName: 'Topic Subject',
    TopicMessage: 'Topic Message',
    Topic: 'Topic',
    By: 'By',
    Forums: 'Forums',
    PostName: 'Post Subject',
    PostContent: 'Post Content',
    SubjectRequired: 'Subject is required',
    ContentRequired: 'Content is required',
    EditPost: 'Edit Post',
    ReplyPost: 'Reply Post',
    EditTopic: 'Edit Topic',
    Post: 'Post',
    Answered: 'Answered',
    NotAnswered: 'Not Answered',
    LoadMore: "Load More",
    NewPosts: "New Post(s)",
    IsFetching: 'isFetching',
    FetchingEnabled: "Enabled",
    FetchingDisabled: "Disbled",
    TopicDescription: 'Topic Description',
    PrevPage: "< Prev Page",
    NextPage: "Next Page >",
    Reload: "Reload",
    RefreshInterval: "Forums Refresh Interval",
    RefreshIntervalInSec:
      "Refresh Interval in seconds (zero means no Refresh Interval)"
  }
});